# Generated by Django 4.1.5 on 2023-01-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва товару')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField(verbose_name='Ціна')),
                ('availability', models.BooleanField(default=True, verbose_name='Наявність')),
                ('group', models.CharField(choices=[("Двері в під'їзд", "Двері в під'їзд"), ('Двері вхідні в будинок', 'Двері вхідні в будинок'), ('Прихований монтаж', 'Прихований монтаж'), ('Двері вхідні в квартиру', 'Двері вхідні в квартиру'), ('Двері протипожежні', 'Двері протипожежні'), ('Міжкімнатні двері', 'Міжкімнатні двері')], default='Двері вхідні в квартиру', max_length=40, verbose_name='Категорія')),
                ('img', models.ImageField(default='no_image.png', upload_to='product_image', verbose_name='Фото')),
                ('description', models.TextField(max_length=1000, verbose_name='Опис')),
                ('door_package', models.TextField(max_length=255, verbose_name='Комплектація')),
                ('door_size', models.TextField(max_length=255, verbose_name='Розміри дверей')),
                ('door_leaf', models.TextField(max_length=255, verbose_name='Дверне полотно')),
                ('threshold', models.TextField(max_length=255, verbose_name='Поріг')),
                ('furniture', models.TextField(max_length=1000, verbose_name='Фурнітура')),
                ('coating', models.CharField(max_length=100, verbose_name='Покриття')),
            ],
        ),
    ]
