# Generated by Django 4.1.5 on 2023-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coating',
            field=models.CharField(max_length=1000, verbose_name='Покриття'),
        ),
        migrations.AlterField(
            model_name='product',
            name='door_package',
            field=models.TextField(max_length=1000, verbose_name='Комплектація'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Двері вхідні в квартиру', 'Двері вхідні в квартиру'), ('Двері вхідні в будинок', 'Двері вхідні в будинок'), ('Прихований монтаж', 'Прихований монтаж'), ('Міжкімнатні двері', 'Міжкімнатні двері'), ('Двері протипожежні', 'Двері протипожежні'), ("Двері в під'їзд", "Двері в під'їзд")], default='Двері вхідні в квартиру', max_length=40, verbose_name='Категорія'),
        ),
    ]
